# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  release:
    types: [published]
  workflow_dispatch:
    
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build phar
      uses: docker://phpdoc/phar-ga:master 
      with:
        args: -d ./src -t ./docs
    - run: ls
    
